# Generated by Django 5.0.4 on 2024-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileRecharge', '0009_delete_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprators',
            name='oprator_code',
        ),
        migrations.AlterField(
            model_name='oprators',
            name='oprator_name',
            field=models.TextField(blank=True, choices=[('Aircel', 'Aircel'), ('Airtel', 'Airtel'), ('BSNL', 'BSNL'), ('Idea', 'Idea'), ('Jio', 'Jio'), ('MTNL', 'MTNL'), ('Reliance', 'Reliance'), ('Tata Docomo', 'Tata Docomo'), ('Telenor', 'Telenor'), ('Uninor', 'Uninor'), ('Vodafone', 'Vodafone')], null=True),
        ),
    ]
